// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IMAGEASSOCIATIONSCHEMA_IMAGEASSOCIATIONMODEL_H_
#define FLATBUFFERS_GENERATED_IMAGEASSOCIATIONSCHEMA_IMAGEASSOCIATIONMODEL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace ImageAssociationModel {

struct ImageGroup;
struct ImageGroupBuilder;

struct ModelData;
struct ModelDataBuilder;

struct ImageGroup FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageGroupBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IMAGE_INDICES = 4
  };
  const ::flatbuffers::Vector<uint32_t> *image_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_IMAGE_INDICES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IMAGE_INDICES) &&
           verifier.VerifyVector(image_indices()) &&
           verifier.EndTable();
  }
};

struct ImageGroupBuilder {
  typedef ImageGroup Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_image_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> image_indices) {
    fbb_.AddOffset(ImageGroup::VT_IMAGE_INDICES, image_indices);
  }
  explicit ImageGroupBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImageGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImageGroup>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImageGroup> CreateImageGroup(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> image_indices = 0) {
  ImageGroupBuilder builder_(_fbb);
  builder_.add_image_indices(image_indices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ImageGroup> CreateImageGroupDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *image_indices = nullptr) {
  auto image_indices__ = image_indices ? _fbb.CreateVector<uint32_t>(*image_indices) : 0;
  return ImageAssociationModel::CreateImageGroup(
      _fbb,
      image_indices__);
}

struct ModelData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IMAGE_FILENAMES = 4,
    VT_IMAGE_GROUPS = 6
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *image_filenames() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>> *>(VT_IMAGE_FILENAMES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>> *image_groups() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>> *>(VT_IMAGE_GROUPS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_IMAGE_FILENAMES) &&
           verifier.VerifyVector(image_filenames()) &&
           verifier.VerifyVectorOfStrings(image_filenames()) &&
           VerifyOffset(verifier, VT_IMAGE_GROUPS) &&
           verifier.VerifyVector(image_groups()) &&
           verifier.VerifyVectorOfTables(image_groups()) &&
           verifier.EndTable();
  }
};

struct ModelDataBuilder {
  typedef ModelData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_image_filenames(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> image_filenames) {
    fbb_.AddOffset(ModelData::VT_IMAGE_FILENAMES, image_filenames);
  }
  void add_image_groups(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>>> image_groups) {
    fbb_.AddOffset(ModelData::VT_IMAGE_GROUPS, image_groups);
  }
  explicit ModelDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelData> CreateModelData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<::flatbuffers::String>>> image_filenames = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>>> image_groups = 0) {
  ModelDataBuilder builder_(_fbb);
  builder_.add_image_groups(image_groups);
  builder_.add_image_filenames(image_filenames);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelData> CreateModelDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<::flatbuffers::String>> *image_filenames = nullptr,
    const std::vector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>> *image_groups = nullptr) {
  auto image_filenames__ = image_filenames ? _fbb.CreateVector<::flatbuffers::Offset<::flatbuffers::String>>(*image_filenames) : 0;
  auto image_groups__ = image_groups ? _fbb.CreateVector<::flatbuffers::Offset<ImageAssociationModel::ImageGroup>>(*image_groups) : 0;
  return ImageAssociationModel::CreateModelData(
      _fbb,
      image_filenames__,
      image_groups__);
}

inline const ImageAssociationModel::ModelData *GetModelData(const void *buf) {
  return ::flatbuffers::GetRoot<ImageAssociationModel::ModelData>(buf);
}

inline const ImageAssociationModel::ModelData *GetSizePrefixedModelData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ImageAssociationModel::ModelData>(buf);
}

inline const char *ModelDataIdentifier() {
  return "CLIA";
}

inline bool ModelDataBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ModelDataIdentifier());
}

inline bool SizePrefixedModelDataBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ModelDataIdentifier(), true);
}

inline bool VerifyModelDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<ImageAssociationModel::ModelData>(ModelDataIdentifier());
}

inline bool VerifySizePrefixedModelDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<ImageAssociationModel::ModelData>(ModelDataIdentifier());
}

inline const char *ModelDataExtension() {
  return "clia";
}

inline void FinishModelDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ImageAssociationModel::ModelData> root) {
  fbb.Finish(root, ModelDataIdentifier());
}

inline void FinishSizePrefixedModelDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ImageAssociationModel::ModelData> root) {
  fbb.FinishSizePrefixed(root, ModelDataIdentifier());
}

}  // namespace ImageAssociationModel

#endif  // FLATBUFFERS_GENERATED_IMAGEASSOCIATIONSCHEMA_IMAGEASSOCIATIONMODEL_H_
